-- Skrip Kemas Kini Skema Pangkalan Data untuk Ciri Pengurusan EFEIS

-- 1. Jadual Baru: efeis_siri_kursus
--    - Untuk menjejak setiap siri kursus yang dijalankan.
CREATE TABLE IF NOT EXISTS public.efeis_siri_kursus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pendapatan_id BIGINT REFERENCES public.pendapatan_lain(id) ON DELETE SET NULL,
    nama_siri TEXT NOT NULL,
    jenis_kursus TEXT NOT NULL CHECK (jenis_kursus IN ('Basic', 'Refresher')),
    tarikh_mula DATE NOT NULL,
    tarikh_tamat DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id)
);
COMMENT ON TABLE public.efeis_siri_kursus IS 'Jadual untuk setiap siri kursus EFEIS yang dijalankan.';

-- 2. Kemas Kini Jadual: peserta_kursus
--    - Menambah lajur baru untuk menjejak status dan kemajuan peserta.
ALTER TABLE public.peserta_kursus
ADD COLUMN IF NOT EXISTS siri_id BIGINT REFERENCES public.efeis_siri_kursus(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS kategori_peserta TEXT CHECK (kategori_peserta IN ('Individu', 'Syarikat')),
ADD COLUMN IF NOT EXISTS status_ujian_teori TEXT DEFAULT 'Belum Ambil' CHECK (status_ujian_teori IN ('Belum Ambil', 'Lulus', 'Gagal', 'Ulang')),
ADD COLUMN IF NOT EXISTS status_ujian_praktikal TEXT DEFAULT 'Belum Ambil' CHECK (status_ujian_praktikal IN ('Belum Ambil', 'Lulus', 'Gagal', 'Ulang')),
ADD COLUMN IF NOT EXISTS tarikh_pendaftaran_syarikat DATE;

-- Nota: Lajur 'nama_syarikat' sedia ada boleh digunakan untuk nama syarikat yang disertai.

-- 3. Jadual Baru: sijil_peserta
--    - Merekodkan sejarah dan kitaran hayat setiap sijil yang dikeluarkan.
CREATE TABLE IF NOT EXISTS public.sijil_peserta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peserta_id BIGINT NOT NULL REFERENCES public.peserta_kursus(id) ON DELETE CASCADE,
    siri_id BIGINT NOT NULL REFERENCES public.efeis_siri_kursus(id),
    no_sijil TEXT UNIQUE,
    tarikh_dikeluarkan DATE,
    tarikh_luput DATE,
    status_sijil TEXT DEFAULT 'Menunggu' NOT NULL CHECK (status_sijil IN ('Aktif', 'Luput', 'Menunggu Pendaftaran Syarikat', 'Batal')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
COMMENT ON TABLE public.sijil_peserta IS 'Merekodkan sejarah dan status setiap sijil EFEIS.';

-- 4. Jadual Baru: efeis_kos_operasi
--    - Merekodkan kos operasi yang terlibat untuk setiap siri kursus EFEIS.
CREATE TABLE IF NOT EXISTS public.efeis_kos_operasi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siri_id BIGINT NOT NULL REFERENCES public.efeis_siri_kursus(id) ON DELETE CASCADE,
    makan_minum NUMERIC(10, 2) DEFAULT 0.00,
    gas_refill NUMERIC(10, 2) DEFAULT 0.00,
    kelas NUMERIC(10, 2) DEFAULT 0.00,
    elaun_pengajar NUMERIC(10, 2) DEFAULT 0.00,
    kos_lain NUMERIC(10, 2) DEFAULT 0.00,
    catatan_kos_lain TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id),
    UNIQUE(siri_id) -- Memastikan hanya ada satu rekod kos untuk setiap siri
);
COMMENT ON TABLE public.efeis_kos_operasi IS 'Jadual untuk merekodkan kos operasi bagi setiap siri kursus EFEIS.';

